name: A workflow for my Hello World action
on: push

jobs:
  build:
    name: Run the evaluacion action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./evaluacion_1
        with:
          N_FIND: 12
